### ISSUE TITLE
Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\ionic app\ionicc1\node_modules\@ionic\storage\es2015\storage.d.js.map'     at Error (native)

### ISSUE THREAD

**Issue by abmnukmr** [ionic-team/ionic-storage#116]
Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\ionic app\ionicc1\node_modules\@ionic\storage\es2015\storage.d.js.map'
    at Error (native)
    at Object.<anonymous> (http://localhost:8100/build/main.js:102719:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:102452:94)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:146922:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

**Comment by mhartington** [comment]
Hi there! It appears that you've opened an issue, but have not provided the necessary information we require in order to debug. Im going to close this issue because of that. Please open a **new** issue and completely fill out the issue template. Thanks!
