### ISSUE TITLE
Error: No available storage method found

### ISSUE THREAD

**Issue by telran** [ionic-team/ionic-storage#139]
Hello,

if I use "@ ionic/storage", I get the following error during the test run with "JEST". (All tests work.)

```
    console.error node_modules/zone.js/dist/zone.js:682
      Unhandled Promise rejection: No available storage method found. ; Zone: <root> ; Task: Promise.then ; Value: Error: No available storage method found.
          at /home/telran/Projekte/app/node_modules/@ionic/storage/node_modules/localforage/dist/localforage.js:2247:25
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/home/telran/Projekte/app/node_modules/zone.js/dist/zone.js:390:26) Error: No available storage method found.
          at /home/telran/Projekte/app/node_modules/@ionic/storage/node_modules/localforage/dist/localforage.js:2247:25
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/home/telran/Projekte/app/node_modules/zone.js/dist/zone.js:390:26)

```

```
  Storage.service.ts
  
  public constructor(@Inject(Storage) private storage: IStorage) {
  }
```
```
  app.module.ts
	
  IonicStorageModule.forRoot({
    name: 'storage',
    driverOrder: ['sqlite', 'websql'],
  }),
```

Environment:
"@ angular/core": "5.1.2",
"@ ionic/storage": "2.1.3",
"rxjs": "5.5.5",
"zone.js": "0.8.19",
"jest": "21.2.1",
"typescript": "2.4.2"

PS: Only the storage needs to be injected to trigger this error.

**Comment by telran** [comment]
We found a solutions: 
- add 'localstorage' to driverOrder
- add jest-localstorage-mock to jestSetup

**Comment by alitalaee** [comment]
it is really easy just :
add ‘localstorage’ to driverOrder
like this::
** IonicStorageModule.forRoot({**
** name: “Database”,**
** driverOrder: [“indexeddb”, “localstorage”]**
** }),**
