### ISSUE TITLE
OpaqueToken Error

### ISSUE THREAD

**Issue by umutgur** [ionic-team/ionic-storage#142]
Hi there,
I want to implement JWT for my mobile application. But I got an error I could not catch. I get an error like this when I want to run my mobile app on the browser;

```
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.OpaqueToken is not a constructor
at Object.<anonymous> (storage.js:230)
at __webpack_require__ (bootstrap 1eb62cb7ba312b8c5f2e:54)
at Object.defineProperty.value (vendor.js:60850)
at __webpack_require__ (bootstrap 1eb62cb7ba312b8c5f2e:54)
at Object.159 (main.js:56)
at __webpack_require__ (bootstrap 1eb62cb7ba312b8c5f2e:54)
at Object.161 (main.js:201)
at __webpack_require__ (bootstrap 1eb62cb7ba312b8c5f2e:54)
at Object.700 (main.js:950)
at __webpack_require__ (bootstrap 1eb62cb7ba312b8c5f2e:54)
```

If I try to run it on my phone I get an error like;

```
[20:10:38]  typescript: .../node_modules/@ionic/storage/es2015/storage.d.ts, line: 2
            Module
            '"/node_modules/@angular/core/core"' has
            no exported member 'OpaqueToken'.

       L1:  import { OpaqueToken } from '@angular/core';
       L3:   * Storage is an easy way to store key/value pairs and JSON objects.

Error: Failed to transpile program
    at new BuildError (..\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at ..\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (..\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (..\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at ..\node_modules\@ionic\app-scripts\dist\build.js:109:82
    at <anonymous>
```

```
cli packages: (..\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by Inframatic** [comment]
This seems to be a big issue at the moment but I havent seen anyone successfully solve it.

**Comment by d-das** [comment]
Is anybody working on this?
A quick workaround was downgrading (`npm i @ionic/storage@2.1.1`), but I'm not sure if this is ok.
Basic googling brought about a bunch of similar errors from [flex-layout](https://github.com/angular/flex-layout/issues/494l), but I'm not sure if this is relevant.

**Comment by roymrunal** [comment]
> Remove `localStorage.setItem()` or `localStorage.removeItem()` inside the app.

I have also got the same issue.
What I found, I was use `localStorage` for storing the value in browser.
Then I remove `localStorage`, and its working fine now.

**Comment by arjuntraj** [comment]
@danbucholtz  any fix ?

**Comment by sunnydrall** [comment]
any updates on this issue?

**Comment by charlesfamu** [comment]
`npm install --save @ionic/storage@2.1.2`

The release notes don't mention v2.1.2. OpaqueToken was deprecated in Angular v5.

**Comment by SURESHA2** [comment]
getting Error : Any budy can solve this?????
 Module '"/home/nanda/IonicApps/myApp2/node_modules/@angular/core/core"' has no exported member 'Slides'.
import Slides
