### ISSUE TITLE
Error when running an Ionic 5 project using @ionic/storage-angular@3.x

### ISSUE THREAD

**Issue by andutoptal** [ionic-team/ionic-storage#250]
Hi, I have set up @ionic/storage-angular according to the documentation available and yet I am getting the error shown in the screenshot I am attaching in the provideStorage function exported from the @ionic/storage-angular project.

Am I missing something? Or is there an issue with the library? I do have to say that using `this` in the provideStorage function seems at least a bit suspicious to me, what instance is this function attached to supposedly?

Thanks.

https://github.com/ionic-team/ionic-storage/blob/ff9183c6e903798da833e372a8d6c037df21f005/angular/src/index.ts#L40

<img width="534" alt="image" src="https://user-images.githubusercontent.com/47985547/157118620-9f9c7812-f396-488a-9277-72a96df8f6d9.png">

**Comment by JonLevy** [comment]
I've been looking at this, as well, and the code does seems problematic.  It is from a new patch that uses a `NoopStorage` instance "when running in a server context."  This breaks the code for us.

**Comment by cyberguilletell** [comment]
I have the same issue

```
TypeError: Cannot read properties of undefined (reading 'platformId')
    at provideStorage (ionic-storage-angular.js:49:25)
    at _callFactory (core.js:24036:1)
    at _createProviderInstance (core.js:23992:1)
    at resolveNgModuleDep (core.js:23950:1)
    at NgModuleRef_.get (core.js:24506:1)
    at resolveDep (core.js:24875:1)
    at createClass (core.js:24760:1)
    at createDirectiveInstance (core.js:24631:1)
    at createViewNodes (core.js:31889:1)
    at createRootView (core.js:31798:1)

```

I followed  this answer
- https://stackoverflow.com/a/69760949/2399444

And it solves that error, but now I got another

```
core.js:6479 ERROR Error: Uncaught (in promise): ReferenceError: Cannot access 'GeneralService' before initialization
ReferenceError: Cannot access 'GeneralService' before initialization
    at Module.GeneralService (auth.service.ts:21:25)
    at AuthService.ctorParameters (auth.service.ts:9:10)
    at ReflectionCapabilities._ownParameters (core.js:4538:1)
    at ReflectionCapabilities.parameters (core.js:4563:1)
    at convertInjectableProviderToFactory (core.js:13808:1)
    at render2CompileInjectable (core.js:13837:1)
    at ɵ0$a (core.js:13821:1)
    at TypeDecorator (core.js:3711:1)
    at __decorate (tslib.es6.js:58:53)
    at 37556 (auth.service.ts:21:25)
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1321:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.js:28681:1)
    at ZoneDelegate.invokeTask (zone.js:433:1)
    at Zone.runTask (zone.js:205:1)
    at drainMicroTaskQueue (zone.js:620:1)
```

I build my code  in a machine with OS = Windows 10 and I don't have any issue, but when I try in a
MacBook Pro (13-inch, M2, 2022)  I have the issues mentioned above
