### ISSUE TITLE
NullInjectorError: StaticInjectorError(AppModule)[Storage]

### ISSUE THREAD

**Issue by chiragDesaiPantherCodx** [ionic-team/ionic-storage#255]
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[Storage]: 
  StaticInjectorError(Platform: core)[Storage]: 
    NullInjectorError: No provider for Storage!
NullInjectorError: StaticInjectorError(AppModule)[Storage]: 
  StaticInjectorError(Platform: core)[Storage]: 
    NullInjectorError: No provider for Storage!
    at NullInjector.get (core.js:855:1)
    at resolveToken (core.js:17514:1)
    at tryResolveToken (core.js:17440:1)
    at StaticInjector.get (core.js:17266:1)
    at resolveToken (core.js:17514:1)
    at tryResolveToken (core.js:17440:1)
    at StaticInjector.get (core.js:17266:1)
    at resolveNgModuleDep (core.js:30393:1)
    at NgModuleRef_.get (core.js:31578:1)
    at injectInjectorOnly (core.js:734:1)
    at resolvePromise (zone-evergreen.js:797:1)
    at resolvePromise (zone-evergreen.js:754:1)
    at zone-evergreen.js:858:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:391:1)
    at Object.onInvokeTask (core.js:39680:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390:1)
    at Zone.runTask (zone-evergreen.js:168:1)
    at drainMicroTaskQueue (zone-evergreen.js:559:1)

i am face this error.

**Comment by chiragDesaiPantherCodx** [comment]
package.josn file :- 
{
  "name": "eleosAppDemo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/app-version": "^5.22.0",
    "@ionic-native/camera": "^5.21.5",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.25.0",
    "@ionic-native/file-transfer": "^5.21.6",
    "@ionic-native/image-picker": "^5.21.5",
    "@ionic-native/in-app-browser": "^5.27.0",
    "@ionic-native/ionic-webview": "^5.25.0",
    "@ionic-native/keyboard": "^5.21.5",
    "@ionic-native/network": "^5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.1.0",
    "hammerjs": "^2.0.8",
    "ngx-material-timepicker": "^5.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "typescript": "~3.5.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {}
  }
}

**Comment by chiragDesaiPantherCodx** [comment]
app.module.ts file :-
{
  "name": "eleosAppDemo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/app-version": "^5.22.0",
    "@ionic-native/camera": "^5.21.5",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.25.0",
    "@ionic-native/file-transfer": "^5.21.6",
    "@ionic-native/image-picker": "^5.21.5",
    "@ionic-native/in-app-browser": "^5.27.0",
    "@ionic-native/ionic-webview": "^5.25.0",
    "@ionic-native/keyboard": "^5.21.5",
    "@ionic-native/network": "^5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.1.0",
    "hammerjs": "^2.0.8",
    "ngx-material-timepicker": "^5.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "typescript": "~3.5.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {}
  }
}
